# Introduction

**Concept** <br>
Fit a *single GEV distribution* using annual maxima from **pooled data**<br>

**Options**
- **Option1**<br>
    pool all data per location for global stationary and non-stationary analysis<br><br>
- **Option2**<br>
    pool all data per location and year for time-dependent stationary analysis<br>

---
**Additional Notes**
- Using sim_year as the actual year 

**Notes on next steps:**
- 8 models × 680 locations = 5,440 independent analyses >> parallelize code on model level

---
**!!! ToDo**
- make flow diagram of model
- parallelize the code
- CONTINUE add Confidence Intervals for Return Levels

# Import Libraries

In [2]:
import sys
import random
import time
from datetime import datetime
from glob import glob
import warnings

import xarray as xr
from IPython.display import Markdown, display
from pandas import DataFrame

import func_gev as gev
import func_preparation as dbf
import func_plotting as dbplt
import func_utils as ut

warnings.filterwarnings("ignore", category=FutureWarning)

# Settings

In [3]:
path = '../input/Annual_max_DCPP_20260112/'
path_export = '../output/gev_analysis/pooled/'

In [4]:
hindcast_start = 1960
hindcast_end = 2026

In [5]:
return_periods = [10, 25, 50, 100, 200]
plot_period_evolution = ['10-year', '50-year', '100-year']

In [6]:
dic_timing = {}
dic_notes_analysis = {}

In [7]:
colors = [
    '#53354DFF','#7D4F73FF','#B887ADFF','#CAA5C2FF','#DBC3D6FF','#F5F5F5FF','#99E3DDFF',
    '#66D4CCFF','#33C6BBFF','#008A80FF','#005C55FF'
    ]

In [8]:
print_msg = True

export_report=True
display_results = False
save_regression_summary = True

# Import data

In [9]:
dic_timing['import data'] = {}
dic_timing['import data']['start'] = datetime.now()

ls_files = [file for file in glob(path + '*.nc')]
ls_files

['../input/Annual_max_DCPP_20260112/Annual_max_MIROC6.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_MPI-ESM1-2-HR.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_HadGEM3-GC31-MM.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_MRI-ESM2-0.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_BCC-CSM2-MR.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_CMCC-CM2-SR5.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_CanESM5.nc',
 '../input/Annual_max_DCPP_20260112/Annual_max_NorCPM1.nc']

In [10]:
dic_data_per_model = dict()

for en, file in enumerate(ls_files):
    model_name = file.split('/')[-1].split('.nc')[0].split('_')[-1]
    
    print(f'Importing data from model {model_name} ({en+1}/{len(ls_files)})...')
    model_name, ds_model = dbf.import_data_from_file(file) 
    
    dic_data_per_model[model_name] = dict({'raw data': ds_model})

dic_timing['import data']['end'] = datetime.now()

Importing data from model MIROC6 (1/8)...
Importing data from model MPI-ESM1-2-HR (2/8)...
Importing data from model HadGEM3-GC31-MM (3/8)...
Importing data from model MRI-ESM2-0 (4/8)...
Importing data from model BCC-CSM2-MR (5/8)...
Importing data from model CMCC-CM2-SR5 (6/8)...
Importing data from model CanESM5 (7/8)...
Importing data from model NorCPM1 (8/8)...

# Data Preparation 

## BiasCorrection and Selection of valid data 
Note, in case the validity check fails, it will return an error. 

Code parallelization for speed up, using `joblib` - saving ~60% (from 3min30sec down to 1min22sec)

In [11]:
dic_timing['data correction'] = {}
dic_timing['data correction']['start'] = datetime.now()
dic_data_per_model = dbf.data_preparation(ls_files=ls_files, dic_data_per_model=dic_data_per_model)
dic_timing['data correction']['end'] = datetime.now()

In [12]:
display(Markdown("**Data Overview**"))
display(Markdown("**Model · model shape: samples (~sim_years) | ensemble members | valid locations**"))
dic_notes_analysis['data overview'] = ut.create_data_overview(dic_data_per_model,ls_files)

display(Markdown(f"Execution time · {dic_timing['data correction']['end'] - dic_timing['data correction']['start']}sec"))

**Data Overview**

**Model · model shape: samples (~sim_years) | ensemble members | valid locations**

MIROC6 · (680, 2, 7054)
MPI-ESM1-2-HR · (630, 2, 5808)
HadGEM3-GC31-MM · (680, 2, 7216)
MRI-ESM2-0 · (320, 2, 3547)
BCC-CSM2-MR · (630, 2, 5236)
CMCC-CM2-SR5 · (690, 2, 6038)
CanESM5 · (660, 2, 5782)
NorCPM1 · (630, 2, 4558)
Overall, data is available from
        	8 models,
        	3547-7216 locations (originally 11022)
        	320-690 samples per model
        	 - with 63-69 unique sim_years
        	 - between 1961-2029

Execution time · 0:01:13.315906sec

## Pool data per location cross models

from 8 models with up to 680 samples (sim_years) and two members and 3547-7216 locations, pool all data together and group per location
> Restructure multi-model ensemble by site <br>
> - from dic[model] -> shape: (sim_year, ensemble_member, location) <br>
> - to dic[location] -> shape: (sim_year, ensemble_member, model)

In [13]:
dic_timing['data pooling'] = {}
dic_timing['data pooling']['start'] = datetime.now()
ls_notes = []

# ------------------------------------------------------------------------------------------
da_list = []
for model_name, dic_model in dic_data_per_model.items():
    da = dic_model['valid data'] 

    da_loc = dbf.sites_to_location(da)
    da_loc = da_loc.expand_dims(model=[model_name])

    da_list.append(da_loc)

combined = xr.concat(da_list, dim="model", join="outer")
dic_timing['data pooling']['end'] = datetime.now()

display(Markdown(f"\n**Overall, the combined dataset has the following dimensions**"))
message = f"""
        Overview of combined dataset
        \tFinal dimensions: {combined.dims}
        \tShape: {combined.shape}
        \tNumber of models: {combined.model.size}
        \tNumber of locations: {combined.location.size}
        """.strip()
print(message)
ls_notes.append(message)

display(Markdown(f"\n**Create and Store summary of locations for which we have no data in either of the models**"))
missing_locations = dbf.create_summary_location_w_missing_data(
    dic_data_per_model=dic_data_per_model, combined=combined, 
    dir_export='/'.join(path_export.split('/')[:-3]) + '/exploration'
    )
ls_notes.append(f'{len(missing_locations)} locations without any valid data found!')

# ------------------------------------------------------------------------------------------
dic_notes_analysis['data pooling'] = ls_notes

**Overall, the combined dataset has the following dimensions**

Overview of combined dataset
        	Final dimensions: ('model', 'sample', 'member', 'location')
        	Shape: (8, 690, 2, 9589)
        	Number of models: 8
        	Number of locations: 9589

**Create and Store summary of locations for which we have no data in either of the models**

1433 locations without any valid data found!
Loading formatted geocoded file...
Map saved as ../output/exploration/map_missingValidData_3.5kmRadius.html. You can open it in your browser and interact with it.

### Validation Check

In [14]:
dic_timing['data validity check'] = {}
dic_timing['data validity check']['start'] = datetime.now()

# ------------------------------------------------------------------------------------------
list_model_labels = list(dic_data_per_model.keys())

model_ex = random.choice(range(len(list_model_labels)))
model_label = list_model_labels[model_ex]
loc_ex = random.choice(range(dic_data_per_model[model_label]['valid data'].shape[-1]))
print(f"For validity check, use randomly selected model {model_label} and site-id {loc_ex}...")

display(Markdown(f"\n**Overview Original dataArray**"))
data_for_model_for_location, lon_target, lat_target = ut.get_dataset_overview_for_model_at_location(
    dic_data=dic_data_per_model, model_label=model_label, site_id=loc_ex
    )

display(Markdown(f"\n**Overview Revised dataArray**"))
revised_dataset, lon_rev, lat_rev = ut.get_dataset_overview_for_model_at_location(
    dic_data=combined, model_nr=model_ex, lon=lon_target, lat=lat_target
    )

For validity check, use randomly selected model MIROC6 and site-id 3152...

**Overview Original dataArray**

Model MIROC6 (None) - location-ID 3152
Full dataframe (680, 2) vs reduced (529, 2)
coordinates in original dataset lon|lat: 28.05619|36.81284

**Overview Revised dataArray**

Model None (0) - location-ID None
Full dataframe (690, 2) vs reduced (529, 2)
coordinates in original dataset lon|lat: 28.05619|36.81284

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/.venv/lib/python3.12/site-packages/xarray/core/duck_array_ops.py:258: RuntimeWarning: invalid value encountered in cast
  return data.astype(dtype, **kwargs)

In [15]:
if (
    lon_target == lon_rev
    and lat_target == lat_rev
    and data_for_model_for_location.dropna().equals(revised_dataset.dropna()
    )
):
    message = "Validity Check performed successfully"
else:
    message = "Validity Check failed"

dic_timing['data validity check']['end'] = datetime.now()
dic_notes_analysis['data pooling'].append(message + ' ' + str(dic_timing['data validity check']['end']))

# Workflow GEV - Generalized Extreme Value

## OPTION1
Using all data available per location - from all years and models. Currently, selecting a subset of 10 sites, but later will be applied to all locations.

#### Initial trial with subset of 10 locations

In [16]:
dic_timing['GEV approach 1'] = {}
dic_timing['GEV approach 1']['start'] = datetime.now()

# ------------------------------------------------------------------------------------------
list_sites = random.choices(range(combined.shape[-1]),k=10)

dic_data_per_location = {}
for loc_ex in list_sites: 
    data_at_location = combined[:,:,:, loc_ex].to_dataframe().dropna().reset_index()
    data_at_location = data_at_location.rename(columns={'annualMax':'storm_surge'})
    dic_data_per_location[loc_ex] = data_at_location

### Run Analysis

Note, the output is stored as 
- visuals → png
- tabular data (DataFrames) → Parquet
- other objects (dicts, strings, floats) → Pickle

File structure
```results/
├─ location_1/
│   ├─ df.parquet
│   ├─ metrics.pkl
│   └─ notes.pkl
├─ location_2/
│   ├─ df.parquet
│   ├─ metrics.pkl
│   └─ notes.pkl
...
```

In [17]:
orig_stdout, orig_stderr, fh, logger, log_path = ut.initialize_logger(
    f"LOGS_GEVAnalysis_pooled_{datetime.now():%Y%m%d_%H%M%S}.log"
    )

# ------------------------------------------------------------------------------------------
dic_timing['GEV approach 1']['analysis start'] = datetime.now()
ls_notes = []

print("\n" + "="*100)
print("STORM SURGE GEV ANALYSIS - POOLED APPROACH PER LOCATION")
print("="*100)

# ------------------------------------------------------------------------------------------
dic_prepared, notes = ut.prepare_pooled_data(
    dic_data=dic_data_per_location,
    hindcast_start=hindcast_start,
    hindcast_end=hindcast_end
)
ls_notes.append(notes)

# ------------------------------------------------------------------------------------------
results = {}
for loc_id, df_prepared in dic_prepared.items():
    print("\n" + "-"*70)
    print(f"Analyzing location id {loc_id} ...")

    lon_loc = df_prepared.lon.unique()[0]
    lat_loc = df_prepared.lat.unique()[0]

    print("\tLookup location info...")
    location_closest = dbf.add_location_labels(DataFrame([lon_loc, lat_loc], index=['lon', 'lat']).T)
    location_info = ' '.join(location_closest.values[0][2:])
    print(f"\t → Closest location identified: {location_info}")

    result, ls_warnings = gev.analyze_per_location(
        df_prepared, loc_id, lat_loc, lon_loc, location_info, return_periods
    )
    if any(ls_warnings):
        ls_notes.append(ls_warnings)
    
    if result is None:
        message = f"\t→ Warning! No valid GEV fit for location id {loc_id}. Skipping ..."
        print(message)
        ls_notes.append(message)
        continue
    
    if export_report and path_export: 
        export_path_site = ut.save_location_results(            
            location_id=loc_id, result_location=result, base_dir=path_export, 
            plot_period_evolution=plot_period_evolution, display_results=display_results
            )

    result['file_path_report'] = export_path_site
    results[loc_id] = result

# ------------------------------------------------------------------------------------------
dic_timing['GEV approach 1']['analysis end'] = datetime.now()

print("\n" + "="*100)
time_diff = dic_timing['GEV approach 1']['analysis end'] - dic_timing['GEV approach 1']['analysis start']
print(f"✓ ANALYSIS COMPLETED IN {time_diff}!")
print("="*100)

# ------------------------------------------------------------------------------------------
dic_notes_analysis['GEV pooled analysis'] = ls_notes
sys.stdout = orig_stdout
sys.stderr = orig_stderr
logger.removeHandler(fh)
fh.close()

10 locations require an execution time of ~ 30-50sec<br> 
Upscaling to 11022 locations, will result in an execution time of ~9-10hours!

## OPTION2
Re-run stationary GEV per year (for location parameter; scale and shape remain as globally defined)

In [18]:
# del results
try:
    results.keys()
    print('✓ continue with available dictionary')
    
except NameError:
    print('import data from files...')
    results = ut.import_results_from_files(path_export)

✓ continue with available dictionary

In [19]:
dic_timing['GEV approach 2'] = {}
dic_timing['GEV approach 2']['analysis start'] = datetime.now()

# ------------------------------------------------------------------------------------------
results_extended, ls_notes_analysis = gev.execute_and_store_stat_gev_per_year(
    results=results, store_results=True, return_periods=return_periods
    )

# ------------------------------------------------------------------------------------------
for key, outer_list in ls_notes_analysis.items():
    ls_notes_analysis[key] = [inner for inner in outer_list if inner]
dic_notes_analysis['annual_statGEV'] = ls_notes_analysis
dic_timing['GEV approach 2']['analysis end'] = datetime.now()

# ------------------------------------------------------------------------------------------
time_diff = dic_timing['GEV approach 2']['analysis end'] - dic_timing['GEV approach 2']['analysis start']
print(f"Execution time for computing GEV per year: {time_diff}sec")

Conducting stationary GEV for siteID 2534 (#1 out of 10) grouped per year...
Warning: Only 8 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 3217 (#2 out of 10) grouped per year...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 2887 (#3 out of 10) grouped per year...
Warning: Only 8 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 5272 (#4 out of 10) grouped per year...
Warning: Only 2 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...
Warning: Only 4 observations in 1962. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1962.0...
Warning: Only 6 observations in 1963. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1963.0...
Warning: Only 7 observations in 1964. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1964.0...
Warning: Only 9 observations in 1965. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1965.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 4780 (#5 out of 10) grouped per year...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 5001 (#6 out of 10) grouped per year...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 1353 (#7 out of 10) grouped per year...
Warning: Only 4 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...
Warning: Only 8 observations in 1962. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1962.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 6938 (#8 out of 10) grouped per year...
Warning: Only 2 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...
Warning: Only 4 observations in 1962. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1962.0...
Warning: Only 6 observations in 1963. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1963.0...
Warning: Only 7 observations in 1964. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1964.0...
Warning: Only 9 observations in 1965. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1965.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 7054 (#9 out of 10) grouped per year...
Warning: Only 4 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...
Warning: Only 8 observations in 1962. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1962.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Conducting stationary GEV for siteID 2300 (#10 out of 10) grouped per year...
Warning: Only 8 observations in 1961. Need at least 10 for reliable GEV fit.
	skipping Return Level Calculation, no stationary GEV for 1961.0...

/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:375: RuntimeWarning: invalid value encountered in sqrt
  ci_lower = z_T - 1.96 * sqrt(var_z)
/Users/silviazieger/Coding/Python/UniCat_SeaLevelExtremes/script/func_gev.py:376: RuntimeWarning: invalid value encountered in sqrt
  ci_upper = z_T + 1.96 * sqrt(var_z)

	...2026 (#66 out of 66 years)
Done!

Execution time for computing GEV per year: 0:00:38.261024sec

Execution time for 10 locations ~ 40sec<br> 
Upscaling to 11022 locations, will result in an execution time of ~12.5hours!

### Regression of location parameter over years
including uncertainty given by n_obs

**NOTE**<br>
> centering the year parameter due to the following warning:<br>
*"The condition number is large, 2.37e+05. This might indicate that there are strong multicollinearity or other numerical problems."*

In [20]:
dic_timing['GEV approach 2']['regression start'] = datetime.now()

# ------------------------------------------------------------------------------------------
en = 0
for site_id, dic_location in results_extended.items():
    en+=1
    print(
        f"\nPlotting GEV μ trend analysis for location id {site_id} (#{en}/{len(results_extended.keys())})...", 
        end="\r"
        )
    
    df_stat_gev_per_year = dic_location['fit results']['gev_stationary']['analysis_per_year'].dropna()
    df = df_stat_gev_per_year.reset_index().rename(columns={'index': 'year'})

    global_statgev_shape = dic_location['fit results']['gev_stationary']['shape']
    global_statgev_scale = dic_location['fit results']['gev_stationary']['scale']

    [
        df, wls_delta, weights, y_pred, year_grid, year_mean
        ] = gev.weighted_least_square_regression_annual_location(global_statgev_scale, global_statgev_shape, df)
    results_extended[site_id]['WLSdelta'] = dict({'summary': wls_delta, 'weights': weights})
    
    fig = dbplt.plot_gev_mu_trend(
        df=df,
        weights=weights,
        year_grid=year_grid,
        year_mean=year_mean,
        y_pred=y_pred,
        wls_delta=wls_delta,
        nonstat_years=dic_location['data'].year.values.astype(int), 
        nonstat=dic_location['fit results']['gev_nonstationary'],
        display_results=display_results,
        colors_reg=['#333333FF', '#C88D35FF'],
        markers_color='#99E3DDFF'
        )
    
    if save_regression_summary and ('file location' in dic_location.keys() or 'file_path_report' in dic_location.keys()):
        if 'file location' in dic_location.keys():
            save_path = dic_location['file location']
        else:
            save_path = dic_location['file_path_report']
        with open(save_path + '/WLSdelta_summary.html', 'w') as f:
            f.write( wls_delta.summary().as_html())
        
        lat = str(dic_location['location info']['lat'].round(3))
        lon = str(dic_location['location info']['lon'].round(3))
        country = dic_location['location info']['description'].split(',')[-1].strip()  
        file_name = f"/GEVTrendAnalysis_location_{str(site_id)}_{country}_{lat}|{lon}.png"
        fig.savefig(save_path+file_name, dpi=300, bbox_inches='tight')

    else:
        print("\t skipping saving GEV μ trend analysis ...")

# ------------------------------------------------------------------------------------------
dic_timing['GEV approach 2']['regression end'] = datetime.now()
time_diff = dic_timing['GEV approach 2']['regression end'] - dic_timing['GEV approach 2']['regression start']
print(
    f"\nExecution time for computing regression analysis for annual stationary GEV and non-stationary GEV: "
    f"{time_diff}sec"
    )

Plotting GEV μ trend analysis for location id 2534 (#1/10)...
Plotting GEV μ trend analysis for location id 3217 (#2/10)...
Plotting GEV μ trend analysis for location id 2887 (#3/10)...
Plotting GEV μ trend analysis for location id 5272 (#4/10)...
Plotting GEV μ trend analysis for location id 4780 (#5/10)...
Plotting GEV μ trend analysis for location id 5001 (#6/10)...
Plotting GEV μ trend analysis for location id 1353 (#7/10)...
Plotting GEV μ trend analysis for location id 6938 (#8/10)...
Plotting GEV μ trend analysis for location id 7054 (#9/10)...
Plotting GEV μ trend analysis for location id 2300 (#10/10)...
Execution time for computing regression analysis for annual stationary GEV and non-stationary GEV: 0:00:06.597114sec

In [21]:
sorted(results_extended.keys())

[1353, 2300, 2534, 2887, 3217, 4780, 5001, 5272, 6938, 7054]

# Create high-level Summary

##  Store Run Notes and Warnings

In [22]:
ut.store_analysis_notes(dic_notes_analysis, path_export)

Full log written to ../output/gev_analysis/pooled/2026-02-03_225820_analysisNotes.txt
Full log written to ../output/gev_analysis/pooled/2026-02-03_225820_analysisNotes.txt

# Parameters Summary

In [ ]:
from pandas import concat

In [26]:
site_id = list(results.keys())[0]
site_id

2534

In [27]:
DataFrame([
    results[site_id]['location info']['lat'], 
    results[site_id]['location info']['lon'], 
    results[site_id]['location info']['description']
], index=['lat', 'lon', 'closest point identified']).T

         lat       lon closest point identified
0  43.416662 -4.713838       Llanes Asturias ES

In [28]:
DataFrame([
    results[site_id]['hindcast period'][0], results[site_id]['hindcast period'][1]
    ], index=['start', 'end'], columns=['hindcast period']).T

                 start   end
hindcast period   1961  2026

In [29]:
results[site_id]['fit results']['gev_nonstationary']

{'mu0': np.float64(0.24148905379971997),
 'mu1': np.float64(-0.0008371468235532943),
 'sigma': np.float64(0.04250246453051493),
 'xi': np.float64(-0.17054066847676808),
 'trend_in': 'location',
 'n_obs': 5595,
 'log_likelihood': np.float64(9477.176150284156),
 'aic': np.float64(-18946.352300568313),
 'bic': np.float64(-18919.833786085328),
 'years_mean': np.float64(1994.4899016979446),
 'years_std': np.float64(16.80364539498762),
 'CI': {'mu_pred': array([0.2431575 , 0.2431575 , 0.2431575 , ..., 0.23991924, 0.23991924,
         0.23991924], shape=(5595,)),
  'mu_lower': array([0.24058905, 0.24058905, 0.24058905, ..., 0.23746314, 0.23746314,
         0.23746314], shape=(5595,)),
  'mu_upper': array([0.24572595, 0.24572595, 0.24572595, ..., 0.24237534, 0.24237534,
         0.24237534], shape=(5595,))}}

In [30]:
results[site_id]['fit results']['gev_stationary']

{'shape': np.float64(-0.1705877433056088),
 'location': np.float64(0.24148719581325018),
 'scale': np.float64(0.04251810798327402),
 'n_obs': 5595,
 'log_likelihood': np.float64(9476.155037279677),
 'aic': np.float64(-18946.310074559355),
 'bic': np.float64(-18926.421188697117),
 'dist_type': 'Weibull (Type III)',
 'tail_behavior': 'Light (bounded)',
 'analysis_per_year':          shape  location     scale n_obs log_likelihood         aic  \
 1962 -0.609021  0.268946  0.031376    16      35.483734  -64.967468
 1963   -0.2054  0.245791  0.043037    24      40.353718  -74.707436
 1964 -0.087974   0.24667   0.03746    31      54.421638 -102.843277
 1965 -0.616098  0.237998  0.044057    38       71.64615   -137.2923
 1966 -0.886549  0.256651  0.051015    48      91.346475  -176.69295
 ...        ...       ...       ...   ...            ...         ...
 2022 -0.162681  0.243377   0.04115    66     113.094703 -220.189406
 2023 -0.279281  0.235837  0.047295    58      94.684532 -183.369064
 2024 -0.200049  0.240495  0.047009    48      76.946278 -147.892556
 2025 -0.537335  0.247002  0.038187    38      75.417168 -144.834336
 2026 -0.285146  0.233658  0.048306    28      45.244845  -84.489689

              bic           dist_type    tail_behavior
 1962  -62.649702  Weibull (Type III)  Light (bounded)
 1963  -71.173274  Weibull (Type III)  Light (bounded)
 1964  -98.541315  Weibull (Type III)  Light (bounded)
 1965 -132.379541  Weibull (Type III)  Light (bounded)
 1966 -171.079347  Weibull (Type III)  Light (bounded)
 ...          ...                 ...              ...
 2022 -213.620442  Weibull (Type III)  Light (bounded)
 2023 -177.187735  Weibull (Type III)  Light (bounded)
 2024 -142.278953  Weibull (Type III)  Light (bounded)
 2025 -139.921577  Weibull (Type III)  Light (bounded)
 2026  -80.493076  Weibull (Type III)  Light (bounded)

 [65 rows x 9 columns],
 'return_levels_per_year':       10-year_return_level  10-year_CI_lower  10-year_CI_upper  \
 Year
 1962              0.307381          0.099310          0.515452
 1963              0.323341          0.099838          0.546845
 1964              0.323148          0.145409          0.500887
 1966              0.306368          0.111781          0.500954
 1968              0.307279         -0.008212          0.622770
 1969              0.333335          0.160734          0.505935
 1970              0.327448          0.265463          0.389432
 1971              0.335164          0.244553          0.425775
 1972              0.315992         -0.051571          0.683556
 1973              0.318337          0.194741          0.441933
 1974              0.311545          0.206787          0.416304
 1975              0.323351          0.075747          0.570956
 1977              0.325081          0.251954          0.398208
 1978              0.316011          0.236218          0.395803
 1979              0.323292          0.265231          0.381352
 1980              0.311634          0.232142          0.391125
 1983              0.304002          0.080583          0.527420
 1984              0.323879          0.242934          0.404825
 1985              0.325126          0.221908          0.428343
 1986              0.318297          0.238564          0.398029
 1987              0.323652          0.246048          0.401257
 1988              0.320505          0.249468          0.391542
 1989              0.310474          0.222037          0.398911
 1990              0.320710          0.207788          0.433632
 1993              0.331093          0.198823          0.463362
 1997              0.324959          0.215923          0.433995
 1998              0.327228          0.218654          0.435802
 1999              0.319188          0.162426          0.475951
 2001              0.325940          0.195038          0.456843
 2003              0.314906          0.069345          0.560468
 2004              0.312404          0.193998          0.430810
 2005              0.325309          0.247693          0.402924
 2007              0.310597          0.208203          0.412990
 2009              0.322432          0.189377          0.455486
 2010              0.329653          0.194213          0.465092
 2011              0.316453          0.217071          0.415836
 2012              0.299180          0.113621          0.484739
 2013              0.305884          0.203087          0.408681
 2014              0.318515          0.213021          0.424010
 2015              0.323848          0.082375          0.565322
 2017              0.323563          0.233421          0.413705
 2018              0.319968         -0.338816          0.978751
 2019              0.321725          0.166377          0.477073
 2020              0.313508          0.221882          0.405134
 2021              0.322675          0.231116          0.414233
 2022              0.320921          0.215536          0.426307
 2023              0.314853          0.099247          0.530458
 2024              0.325675          0.162399          0.488952
 2025              0.296860         -0.440350          1.034070
 2026              0.313889          0.149251          0.478527

       25-year_return_level  25-year_CI_lower  25-year_CI_upper  \
 Year
 1962              0.313121          0.105435          0.520806
 1963              0.346696          0.125742          0.567651
 1964              0.351105          0.175562          0.526647
 1966              0.310817          0.116466          0.505169
 1968              0.313669         -0.000706          0.628045
 1969              0.361697          0.192176          0.531219
 1970              0.353039          0.291328          0.414749
 1971              0.363822          0.274081          0.453564
 1972              0.339773         -0.020878          0.700424
 1973              0.342289          0.221188          0.463389
 1974              0.337830          0.234470          0.441190
 1975              0.349313          0.106570          0.592056
 1977              0.351148          0.278598          0.423699
 1978              0.337399          0.258226          0.416572
 1979              0.347172          0.289120          0.405223
 1980              0.337065          0.258283          0.415846
 1983              0.318842          0.097410          0.540275
 1984              0.350356          0.269971          0.430741
 1985              0.353518          0.251324          0.455712
 1986              0.343394          0.264384          0.422404
 1987              0.347539          0.270616          0.424463
 1988              0.346382          0.275965          0.416799
 1989              0.338908          0.251418          0.426398
 1990              0.345034          0.233739          0.456328
 1993              0.363533          0.234687          0.492379
 1997              0.350333          0.242658          0.458008
 1998              0.355413          0.248553          0.462274
 1999              0.344240          0.190784          0.497696
 2001              0.355342          0.227064          0.483619
 2003              0.340567          0.100161          0.580974
 2004              0.336226          0.219926          0.452526
 2005              0.348927          0.271852          0.426001
 2007              0.340677          0.239740          0.441613
 2009              0.350404          0.220050          0.480758
 2010              0.352695          0.219451          0.485939
 2011              0.341503          0.243692          0.439315
 2012              0.314300          0.130643          0.497957
 2013              0.321823          0.219662          0.423984
 2014              0.345760          0.241624          0.449896
 2015              0.352311          0.116393          0.588229
 2017              0.346685          0.257784          0.435586
 2018              0.340107         -0.309355          0.989569
 2019              0.347941          0.195432          0.500449
 2020              0.336738          0.246138          0.427339
 2021              0.346048          0.255438          0.436658
 2022              0.345994          0.241657          0.450331
 2023              0.335867          0.123123          0.548611
 2024              0.351558          0.190780          0.512336
 2025              0.305326         -0.428222          1.038875
 2026              0.335015          0.171632          0.498399

       50-year_return_level  50-year_CI_lower  50-year_CI_upper  \
 Year
 1962              0.315680          0.108143          0.523217
 1963              0.361309          0.141644          0.580974
 1964              0.370389          0.195757          0.545020
 1966              0.312384          0.118102          0.506665
 1968              0.316274          0.002330          0.630218
 1969              0.379533          0.211720          0.547345
 1970              0.369061          0.307203          0.430919
 1971              0.381998          0.292520          0.471475
 1972              0.354867         -0.001560          0.711293
 1973              0.357573          0.237886          0.477259
 1974              0.355679          0.253008          0.458349
 1975              0.366528          0.126853          0.606203
 1977              0.368010          0.295566          0.440454
 1978              0.350323          0.271373          0.429273
 1979              0.362059          0.303770          0.420348
 1980              0.354451          0.275854          0.433048
 1983              0.327275          0.106912          0.547637
 1984              0.367843          0.287555          0.448132
 1985              0.372769          0.270976          0.474562
 1986              0.360116          0.281333          0.438900
 1987              0.362258          0.285556          0.438959
 1988              0.362637          0.292345          0.432928
 1989              0.358451          0.271236          0.445665
 1990              0.360590          0.250168          0.471012
 1993              0.386085          0.259163          0.513008
 1997              0.366533          0.259526          0.473539
 1998              0.373587          0.267568          0.479606
 1999              0.360420          0.208939          0.511901
 2001              0.375615          0.248799          0.502430
 2003              0.357833          0.120740          0.594926
 2004              0.351389          0.236266          0.466512
 2005              0.363427          0.286493          0.440361
 2007              0.361595          0.261243          0.461947
 2009              0.369619          0.240853          0.498385
 2010              0.366570          0.234499          0.498640
 2011              0.357335          0.260306          0.454364
 2012              0.323192          0.140598          0.505787
 2013              0.330990          0.229122          0.432858
 2014              0.363963          0.260463          0.467462
 2015              0.371183          0.138742          0.603623
 2017              0.360658          0.272323          0.448993
 2018              0.352586         -0.291295          0.996466
 2019              0.364071          0.213124          0.515018
 2020              0.351796          0.261648          0.441945
 2021              0.360344          0.270095          0.450593
 2022              0.362249          0.258322          0.466175
 2023              0.348229          0.137016          0.559443
 2024              0.367825          0.208341          0.527309
 2025              0.309337         -0.422555          1.041229
 2026              0.347383          0.184478          0.510288

       100-year_return_level  100-year_CI_lower  100-year_CI_upper  \
 Year
 1962               0.317338           0.109886           0.524789
 1963               0.373869           0.155116           0.592621
 1964               0.388385           0.214165           0.562606
 1966               0.313219           0.118970           0.507469
 1968               0.317840           0.004144           0.631536
 1969               0.394927           0.228440           0.561415
 1970               0.382840           0.320658           0.445021
 1971               0.397799           0.308368           0.487231
 1972               0.367997           0.015131           0.720863
 1973               0.370930           0.252358           0.489501
 1974               0.372116           0.269894           0.474339
 1975               0.382067           0.145049           0.619086
 1977               0.382915           0.310391           0.455439
 1978               0.361111           0.282255           0.439967
 1979               0.374816           0.316176           0.433456
 1980               0.370554           0.291913           0.449195
 1983               0.333959           0.114408           0.553509
 1984               0.383575           0.303189           0.463962
 1985               0.390476           0.288845           0.492107
 1986               0.375272           0.296518           0.454026
 1987               0.374746           0.298111           0.451381
 1988               0.376654           0.306304           0.447004
 1989               0.376633           0.289405           0.463861
 1990               0.374211           0.264441           0.483981
 1993               0.407272           0.281809           0.532735
 1997               0.380695           0.274142           0.487249
 1998               0.389609           0.284158           0.495061
 1999               0.374705           0.224856           0.524554
 2001               0.394528           0.268817           0.520239
 2003               0.373611           0.139432           0.607789
 2004               0.364613           0.250408           0.478818
 2005               0.375694           0.298761           0.452627
 2007               0.381251           0.281131           0.481371
 2009               0.387489           0.260002           0.514976
 2010               0.378117           0.246929           0.509305
 2011               0.371060           0.274571           0.467548
 2012               0.330448           0.148686           0.512211
 2013               0.338331           0.236655           0.440008
 2014               0.380499           0.277389           0.483608
 2015               0.388215           0.158766           0.617665
 2017               0.372323           0.284348           0.460298
 2018               0.363225          -0.276035           1.002485
 2019               0.377741           0.227998           0.527484
 2020               0.365132           0.275242           0.455021
 2021               0.372400           0.282321           0.462479
 2022               0.376645           0.272903           0.480387
 2023               0.358319           0.148259           0.568379
 2024               0.381859           0.223312           0.540406
 2025               0.312069          -0.418739           1.042876
 2026               0.357435           0.194769           0.520101

       200-year_return_level  200-year_CI_lower  200-year_CI_upper
 Year
 1962               0.318418           0.111016           0.525820
 1963               0.384714           0.166598           0.602830
 1964               0.405250           0.231035           0.579466
 1966               0.313668           0.119433           0.507903
 1968               0.318788           0.005236           0.632341
 1969               0.408276           0.242819           0.573733
 1970               0.394744           0.332138           0.457350
 1971               0.411599           0.322069           0.501129
 1972               0.379472           0.029620           0.729325
 1973               0.382654           0.264964           0.500345
 1974               0.387318           0.285351           0.489285
 1975               0.396154           0.161446           0.630863
 1977               0.396149           0.323418           0.468879
 1978               0.370159           0.291314           0.449003
 1979               0.385798           0.326747           0.444849
 1980               0.385531           0.306667           0.464395
 1983               0.339284           0.120353           0.558215
 1984               0.397789           0.317166           0.478413
 1985               0.406831           0.305176           0.508486
 1986               0.389066           0.310196           0.467936
 1987               0.385392           0.308723           0.462061
 1988               0.388798           0.318273           0.459324
 1989               0.393620           0.306150           0.481090
 1990               0.386190           0.276904           0.495476
 1993               0.427257           0.302860           0.551654
 1997               0.393132           0.286873           0.499391
 1998               0.403798           0.298709           0.508886
 1999               0.387372           0.238879           0.535866
 2001               0.412247           0.287343           0.537150
 2003               0.388090           0.156486           0.619694
 2004               0.376197           0.262709           0.489686
 2005               0.386119           0.309100           0.463138
 2007               0.399797           0.299619           0.499975
 2009               0.404176           0.277709           0.530643
 2010               0.387772           0.257252           0.518293
 2011               0.383010           0.286886           0.479135
 2012               0.336398           0.155290           0.517506
 2013               0.344240           0.242688           0.445792
 2014               0.395585           0.292674           0.498496
 2015               0.403655           0.176788           0.630522
 2017               0.382107           0.294351           0.469863
 2018               0.372336          -0.263082           1.007755
 2019               0.389381           0.240570           0.538191
 2020               0.376993           0.287221           0.466764
 2021               0.382614           0.292579           0.472649
 2022               0.389451           0.285732           0.493170
 2023               0.366594           0.157406           0.575781
 2024               0.394022           0.236148           0.551897
 2025               0.313940          -0.416153           1.044033
 2026               0.365645           0.203068           0.528223  }

In [31]:
results[site_id]['model_comparison']

{'lr_statistic': np.float64(2.042226008958096),
 'df': 1,
 'p_value': np.float64(0.1529856289746101),
 'delta_aic': np.float64(-0.04222600895809592),
 'delta_bic': np.float64(6.5874026117890025),
 'decision': 'No strong evidence for non-stationarity',
 'recommendation': 'Use stationary model (simpler)'}

In [33]:
wls_params = concat([results[site_id]['WLSdelta']['summary'].params, results[site_id]['WLSdelta']['summary'].bse], axis=1)
wls_params.columns = ['value', 'std err']
wls_params

          value   std err
const  0.240149  0.001541
year  -0.000057  0.000092

In [34]:
results[site_id]['WLSdelta']['summary'].summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            WLS Regression Results
==============================================================================
Dep. Variable:               location   R-squared:                       0.006
Model:                            WLS   Adj. R-squared:                 -0.010
Method:                 Least Squares   F-statistic:                    0.3805
Date:                Tue, 03 Feb 2026   Prob (F-statistic):              0.540
Time:                        23:02:54   Log-Likelihood:                 192.23
No. Observations:                  65   AIC:                            -380.5
Df Residuals:                      63   BIC:                            -376.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2401      0.002    155.875      0.000       0.237       0.243
year       -5.665e-05   9.18e-05     -0.617      0.540      -0.000       0.000
==============================================================================
Omnibus:                       43.098   Durbin-Watson:                   2.532
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              196.955
Skew:                          -1.791   Prob(JB):                     1.71e-43
Kurtosis:                      10.739   Cond. No.                         16.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
results[site_id]['return_levels']

{'stationary': {'10-year': {'return_level': np.float64(0.32094401927235994),
   'CI_lower': np.float64(0.3134651322651895),
   'CI_upper': np.float64(0.32842290627953036)},
  '25-year': {'return_level': np.float64(0.3463005741780134),
   'CI_lower': np.float64(0.3388560553965377),
   'CI_upper': np.float64(0.35374509295948914)},
  '50-year': {'return_level': np.float64(0.36263181307832554),
   'CI_lower': np.float64(0.35516562358638426),
   'CI_upper': np.float64(0.3700980025702668)},
  '100-year': {'return_level': np.float64(0.3770157276772595),
   'CI_lower': np.float64(0.369502399406514),
   'CI_upper': np.float64(0.38452905594800496)},
  '200-year': {'return_level': np.float64(0.3897406424451899),
   'CI_lower': np.float64(0.38216417991909396),
   'CI_upper': np.float64(0.39731710497128586)}},
 'nonstationary_start': {'year': 1961,
  'values': {'10-year': {'return_level': np.float64(0.32258902727231187),
    'CI_lower': np.float64(0.3161453533838355),
    'CI_upper': np.float64(0.32903270116078825)},
   '25-year': {'return_level': np.float64(0.34793948870558916),
    'CI_lower': np.float64(0.33994181525483164),
    'CI_upper': np.float64(0.3559371621563467)},
   '50-year': {'return_level': np.float64(0.36426744215016793),
    'CI_lower': np.float64(0.355350379622426),
    'CI_upper': np.float64(0.37318450467790987)},
   '100-year': {'return_level': np.float64(0.37864893756193524),
    'CI_lower': np.float64(0.36899091297430586),
    'CI_upper': np.float64(0.3883069621495646)},
   '200-year': {'return_level': np.float64(0.3913721296129878),
    'CI_lower': np.float64(0.38112194907551855),
    'CI_upper': np.float64(0.401622310150457)}}},
 'nonstationary_end': {'year': 2026,
  'values': {'10-year': {'return_level': np.float64(0.3193507690103757),
    'CI_lower': np.float64(0.31288311912206945),
    'CI_upper': np.float64(0.3258184188986819)},
   '25-year': {'return_level': np.float64(0.344701230443653),
    'CI_lower': np.float64(0.3366693286604359),
    'CI_upper': np.float64(0.35273313222687)},
   '50-year': {'return_level': np.float64(0.36102918388823174),
    'CI_lower': np.float64(0.35207364618013814),
    'CI_upper': np.float64(0.36998472159632534)},
   '100-year': {'return_level': np.float64(0.37541067929999905),
    'CI_lower': np.float64(0.36571138253363045),
    'CI_upper': np.float64(0.38510997606636765)},
   '200-year': {'return_level': np.float64(0.3881338713510516),
    'CI_lower': np.float64(0.3778404876495582),
    'CI_upper': np.float64(0.398427255052545)}}}}

# Next Steps

summarize the intercept, slopes, CIs for different approaches and store results in human-readable format

#### Potential Visualizations
- Maps of 100-year return levels along European coastline
- Difference maps: non-stationary minus stationary → climate change impact
- Probability exceedance curves for selected cities
- Histograms / density of return levels → compare regions
- Time series of non-stationary μ or return levels → show increasing trends

In [ ]:
site_id = 5943
result_location = results_extended[site_id]

result_location.keys()

In [ ]:
result_location['location info']

In [ ]:
result_location['hindcast period'] # years

In [ ]:
# GEV Stationary
result_location['fit results']['gev_stationary']['analysis_per_year']

In [ ]:
# GEV non-Stationary
result_location['fit results']['gev_nonstationary']

In [ ]:
result_location['model_comparison']

In [ ]:
result_location['return_levels']